#!/bin/bash

_scriptpath="$(dirname "$(readlink -f "$0")")"

cd "${_scriptpath}" || { printf '%s' 'Cannot cd to script directory' >&2 ; exit 1 ;}

case "$1" in
  "start")
    python3 "${_scriptpath}/cameras.py" &
  ;;

  "stop")
    echo EXIT > "${_scriptpath}/status"
  ;;

  "gui")
    python3 "${_scriptpath}/gui.py" &
  ;;

  "passthrough")
    echo PASSTHROUGH > "${_scriptpath}/status"
  ;;

  "video")
    echo VIDEO > "${_scriptpath}/status"
  ;;

  "image")
    echo IMAGE > "${_scriptpath}/status"
  ;;

  "status")
    echo Status: "$(cat "${_scriptpath}/status")"
  ;;

  *)
    echo "Usage: zctl [start/stop/status/gui/passthrough/video/image]"
    exit 1
  ;;
esac
